services: 
  bot:
    build: . 
    depends_on:
      - db
    env_file:
      - .env
    command: bash -c "python app.py"
    volumes:
      - .:/code

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_HOST_AUTH_METHOD: ${POSTGRES_HOST_AUTH_METHOD}
      PGDATA: /var/lib/postgresql/data/data_bot/
    ports:
      - 5432:5432
    
  admin:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  postgres_data:
